[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.8",
    "langchain>=0.3.18",
    "langchain-community>=0.3.17",
    "openai>=1.63.0",
    "uvicorn>=0.34.0",
]
